version: '3.9'
services:

  chat_bot_db:
    image: postgres:14.1
    restart: always
    environment:
      #      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: CHATBOTPWD
      POSTGRES_USER: CHATBOTUSER
      POSTGRES_DB: CHATBOTDB
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
