export enum GeneratorType {
  GREETINGS = 'GREETINGS',
  PRODUCTS_DISPLAY = 'PRODUCTS_DISPLAY',
  PRODUCT_DETAILS = 'PRODUCT_DETAILS',
  CART_ACTION = 'CART_ACTION',
  PAYMENT_NOTIFICATION = 'PAYMENT_NOTIFICATION',
  ASK_ACTION = 'ASK_ACTION',
  GOODBYE = 'GOODBYE',
  UNKNOWN = 'UNKNOWN',
}
